"use client";

import * as Switch from "@radix-ui/react-switch";
import { Braces, Clock3, Database, RotateCcw, Settings, SlidersHorizontal } from "lucide-react";
import { toast } from "sonner";
import { PageHeader } from "@/components/page-header";
import { usePreferences } from "@/store/workspace";
import { useActiveConnection } from "@/hooks/use-database";

export function SettingsPage() {
  const preferences = usePreferences();
  const { connection } = useActiveConnection();
  return <div className="page-stack"><PageHeader icon={Settings} eyebrow="Workspace" title="Settings" description="Local editor, results, monitoring, and appearance preferences." actions={<button className="button secondary" onClick={() => { preferences.reset(); toast.success("Preferences reset"); }}><RotateCcw size={14} /> Reset defaults</button>} />
    <div className="settings-layout"><nav className="settings-nav"><a href="#editor"><Braces size={15} /> SQL editor</a><a href="#results"><SlidersHorizontal size={15} /> Results</a><a href="#monitoring"><Clock3 size={15} /> Monitoring</a><a href="#connection"><Database size={15} /> Connection</a></nav><div className="settings-content">
      <SettingsSection id="editor" title="SQL editor" description="Tune the editing and execution experience."><RangeSetting label="Editor font size" description="Font size used by Monaco Editor." value={preferences.editorFontSize} min={11} max={20} suffix="px" onChange={(editorFontSize) => preferences.update({ editorFontSize })} /><SelectSetting label="Execution timeout" description="PostgreSQL statement timeout for each execution." value={String(preferences.timeoutMs)} onChange={(value) => preferences.update({ timeoutMs: Number(value) })} options={[{ value: "10000", label: "10 seconds" }, { value: "30000", label: "30 seconds" }, { value: "60000", label: "60 seconds" }, { value: "120000", label: "120 seconds" }]} /></SettingsSection>
      <SettingsSection id="results" title="Query results" description="Control result display defaults."><SelectSetting label="Default page size" description="Preferred number of rows per page." value={String(preferences.pageSize)} onChange={(value) => preferences.update({ pageSize: Number(value) })} options={[25, 50, 100, 250].map((value) => ({ value: String(value), label: `${value} rows` }))} /><ToggleSetting label="Compact rows" description="Use dense table spacing for database work." checked={preferences.compactRows} onChange={(compactRows) => preferences.update({ compactRows })} /></SettingsSection>
      <SettingsSection id="monitoring" title="Monitoring" description="Choose how often live views are sampled."><SelectSetting label="Refresh interval" description="Automatic refresh for active monitoring pages." value={String(preferences.refreshSeconds)} onChange={(value) => preferences.update({ refreshSeconds: Number(value) })} options={[{ value: "5", label: "5 seconds" }, { value: "15", label: "15 seconds" }, { value: "30", label: "30 seconds" }, { value: "60", label: "1 minute" }]} /></SettingsSection>
      <SettingsSection id="connection" title="Connection information" description="Safe metadata for the currently selected endpoint."><div className="safe-connection"><div><span>Connection</span><strong>{connection?.name ?? "Not configured"}</strong></div><div><span>Database</span><strong>{connection?.database ?? "—"}</strong></div><div><span>Host</span><strong>{connection?.host ?? "—"}</strong></div><div><span>User</span><strong>{connection?.user ?? "—"}</strong></div></div><div className="callout"><Database size={16} /><p>Passwords and full connection strings are intentionally never exposed to the browser.</p></div></SettingsSection>
    </div></div>
  </div>;
}
function SettingsSection({ id, title, description, children }: { id: string; title: string; description: string; children: React.ReactNode }) { return <section className="settings-section" id={id}><div><h2>{title}</h2><p>{description}</p></div><div className="settings-card">{children}</div></section>; }
function RangeSetting({ label, description, value, min, max, suffix, onChange }: { label: string; description: string; value: number; min: number; max: number; suffix: string; onChange: (value: number) => void }) { return <div className="setting-row"><div><strong>{label}</strong><span>{description}</span></div><div className="range-control"><input type="range" min={min} max={max} value={value} onChange={(event) => onChange(Number(event.target.value))} /><output>{value}{suffix}</output></div></div>; }
function SelectSetting({ label, description, value, onChange, options }: { label: string; description: string; value: string; onChange: (value: string) => void; options: { value: string; label: string }[] }) { return <label className="setting-row"><div><strong>{label}</strong><span>{description}</span></div><select value={value} onChange={(event) => onChange(event.target.value)}>{options.map((option) => <option value={option.value} key={option.value}>{option.label}</option>)}</select></label>; }
function ToggleSetting({ label, description, checked, onChange }: { label: string; description: string; checked: boolean; onChange: (value: boolean) => void }) { return <div className="setting-row"><div><strong>{label}</strong><span>{description}</span></div><Switch.Root className="switch" checked={checked} onCheckedChange={onChange}><Switch.Thumb /></Switch.Root></div>; }

