"use client";

import { useQuery } from "@tanstack/react-query";
import * as Tabs from "@radix-ui/react-tabs";
import { ArrowLeft, Copy, Database, GitFork, KeyRound, RefreshCw, Table2 } from "lucide-react";
import Link from "next/link";
import { toast } from "sonner";
import { EmptyState } from "@/components/empty-state";
import { PageHeader } from "@/components/page-header";
import { PageSkeleton } from "@/components/skeleton";
import { fetchJson, useActiveConnection } from "@/hooks/use-database";
import { DatabaseDiagram } from "@/components/database-diagram";

type TableDetails = {
  schema: string; table: string; columns: Record<string, unknown>[]; indexes: Record<string, unknown>[];
  constraints: Record<string, unknown>[]; data: Record<string, unknown>[]; dataColumns: string[]; truncated: boolean;
};

export function TableDetailPage({ schema, table, inline = false, onSelect }: { schema: string; table: string; inline?: boolean; onSelect?: (schema: string, table: string) => void }) {
  const { connectionId } = useActiveConnection();
  const url = `/api/database?connectionId=${encodeURIComponent(connectionId ?? "")}&resource=table&schema=${encodeURIComponent(schema)}&table=${encodeURIComponent(table)}`;
  const { data, isPending, error, refetch, isFetching } = useQuery<TableDetails>({ queryKey: ["table-detail", connectionId, schema, table], queryFn: () => fetchJson(url), enabled: Boolean(connectionId) });
  const definition = data ? buildDefinition(data) : "";
  return <div className={inline ? "table-inspector" : "page-stack"}>{inline ? <div className="table-inspector-head"><div><span className="table-inspector-eyebrow"><Table2 size={15} /> {schema}</span><h2>{table}</h2><p>Columns, records and relationships</p></div><button className="button secondary" onClick={() => refetch()} title="Refresh table"><RefreshCw className={isFetching ? "spin" : ""} size={15} /> Refresh</button></div> : <><Link href="/tables" className="back-link"><ArrowLeft size={14} /> All tables</Link><PageHeader icon={Table2} eyebrow={schema} title={table} description="Inspect records, columns, indexes, constraints, and generated SQL." actions={<button className="button secondary" onClick={() => refetch()}><RefreshCw className={isFetching ? "spin" : ""} size={14} /> Refresh</button>} /></>}
    {!connectionId ? <EmptyState title="No database selected" description="Choose a PostgreSQL connection first." /> : isPending ? <PageSkeleton /> : error || !data ? <EmptyState title="Could not inspect table" description={error?.message ?? "The table is unavailable."} /> : <Tabs.Root className="detail-tabs" defaultValue={inline ? "structure" : "data"}><Tabs.List className="tabs-list"><Tabs.Trigger value="structure">Columns <span>{data.columns.length}</span></Tabs.Trigger><Tabs.Trigger value="data">Data <span>{data.data.length}</span></Tabs.Trigger><Tabs.Trigger value="diagram"><GitFork size={13} /> Diagram</Tabs.Trigger>{["indexes", "constraints", "relationships", "sql"].map((tab) => <Tabs.Trigger value={tab} key={tab}>{tab}</Tabs.Trigger>)}</Tabs.List><Tabs.Content value="structure"><StructureTable rows={data.columns} /></Tabs.Content><Tabs.Content value="data"><DataTable rows={data.data} columns={data.dataColumns} />{data.truncated && <div className="table-note">Showing the first 100 rows. Use the SQL Editor for filtered or larger result sets.</div>}</Tabs.Content><Tabs.Content value="diagram"><DatabaseDiagram selected={{ schema, table }} onSelect={onSelect} /></Tabs.Content><Tabs.Content value="indexes"><MetadataTable rows={data.indexes} /></Tabs.Content><Tabs.Content value="constraints"><MetadataTable rows={data.constraints} /></Tabs.Content><Tabs.Content value="relationships"><MetadataTable rows={data.constraints.filter((row) => row.type === "f")} empty="This table has no outgoing foreign-key relationships." /></Tabs.Content><Tabs.Content value="sql"><div className="code-panel"><button onClick={async () => { await navigator.clipboard.writeText(definition); toast.success("Definition copied"); }}><Copy size={14} /> Copy SQL</button><pre><code>{definition}</code></pre></div></Tabs.Content></Tabs.Root>}
  </div>;
}

function StructureTable({ rows }: { rows: Record<string, unknown>[] }) {
  return <div className="panel data-panel structure-panel"><div className="table-toolbar"><strong>Table structure</strong><span className="row-count">{rows.length} columns</span></div><div className="table-scroll"><table><thead><tr><th>Column</th><th>Data type</th><th>Nullable</th><th>Default</th><th>Details</th></tr></thead><tbody>{rows.map((row) => <tr key={String(row.name)}><td className="structure-name"><span className="structure-column-label"><span className="structure-key-slot">{Boolean(row.primaryKey) && <KeyRound size={14} />}</span><span>{String(row.name)}</span></span></td><td><code>{String(row.type)}</code></td><td><span className={row.nullable ? "nullable-yes" : "nullable-no"}>{row.nullable ? "Yes" : "No"}</span></td><td>{cell(row.default)}</td><td>{row.primaryKey ? <span className="structure-badge">PRIMARY KEY</span> : row.identity ? <span className="structure-badge">IDENTITY</span> : row.comment ? String(row.comment) : <span className="null-value">—</span>}</td></tr>)}</tbody></table></div></div>;
}

function DataTable({ rows, columns }: { rows: Record<string, unknown>[]; columns: string[] }) { return <div className="panel data-panel"><div className="table-toolbar"><span className="row-count">{rows.length} rows</span><span className="table-safety"><KeyRound size={13} /> Read-only preview</span></div>{rows.length ? <div className="table-scroll"><table><thead><tr><th>#</th>{columns.map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index}><td className="row-number">{index + 1}</td>{columns.map((column) => <td key={column}>{cell(row[column])}</td>)}</tr>)}</tbody></table></div> : <EmptyState icon={Database} title="This table is empty" description="Insert records through the SQL Editor." />}</div>; }
function MetadataTable({ rows, empty = "No metadata returned." }: { rows: Record<string, unknown>[]; empty?: string }) { const columns = rows[0] ? Object.keys(rows[0]) : []; return <div className="panel data-panel">{rows.length ? <div className="table-scroll"><table><thead><tr>{columns.map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index}>{columns.map((column) => <td key={column}>{cell(row[column])}</td>)}</tr>)}</tbody></table></div> : <EmptyState title="Nothing to show" description={empty} />}</div>; }
function cell(value: unknown) { if (value == null) return <span className="null-value">NULL</span>; if (typeof value === "boolean") return <span className={`boolean ${value}`}>{String(value)}</span>; return typeof value === "object" ? <code>{JSON.stringify(value)}</code> : String(value); }
function buildDefinition(data: TableDetails) { const quote = (value: string) => `"${value.replaceAll('"', '""')}"`; const columns = data.columns.map((column) => `  ${quote(String(column.name))} ${column.type}${column.identity ? " GENERATED BY DEFAULT AS IDENTITY" : ""}${column.default ? ` DEFAULT ${column.default}` : ""}${column.nullable ? "" : " NOT NULL"}`); const constraints = data.constraints.map((constraint) => `  CONSTRAINT ${quote(String(constraint.name))} ${constraint.definition}`); return `CREATE TABLE ${quote(data.schema)}.${quote(data.table)} (\n${[...columns, ...constraints].join(",\n")}\n);`; }
